### ISSUE TITLE
Window problems with plot graph

### ISSUE THREAD

**Issue by rtguy** [arvehj/jvcprojectortools#10]
Window used for plotting often gets stuck under other windows and will not stay in the foreground (only way to see it sometimes is to just highlight it in the task bar).  Windows also says "Unresponsive" in title bar if you try to drag it or click in it.

**Comment by arvehj** [comment]
I don't know if there is an easy way to fix this, but you can work around the issue for now by running "p s". That will make the window responsive for long enough for you to move it.

**Comment by rtguy** [comment]
I think I read in your release notes that the latest wip commit adds axis and labels. However when I used it last night my plot graph did not have any axis or labels, Also the plot window is still getting stuck under other windows and becomes "unresponsive". This window is so important it would be great if it behaved more like a regular window.  Also I noticed the first "p" command yields nothing drawn. Have to issue it a 2nd time for the first plot to show up, then after there on it does draw with each subsequent p command.

**Comment by rtguy** [comment]
The labels for the axis are now fixed - thank you! However the problem with the plot window being unresponsive and wanting to hide behind all other windows and not come to the foreground still exists - no change there.

**Comment by arvehj** [comment]
Did you try the [threaded_menu](../tree/threaded_menu) branch from #15?

**Comment by rtguy** [comment]
Sorry, I was looking at wip still. OK I just tested it and the plot window is now fixed! Works like a normal window, responsive, doesn't get stuck under other windows etc. Great job, thank you.
