### ISSUE TITLE
Open JVC menu causes timeout on gamma table write

### ISSUE THREAD

**Issue by rtguy** [arvehj/jvcprojectortools#11]
Reproduce:

- Have JVC main menu open, like where it shows you the options to select gamma and brightness/contrast
- issue Pw command
- JVC menu closes which is good, but then a timeout error occurs trying to write red gamma
- tool recovers and writes the gamma, but causes a delay due to the timeout if you forget the close the menu after adjusting contrast and then issuing "3" command, etc.

It would be great if you can autoclose them menu if open and then write without the timeout occurring.

**Comment by arvehj** [comment]
This is a problem caused by the projector. I don't know if there is a command I can send that always closes the menu, but I'll look into it.

**Comment by arvehj** [comment]
#5 now adds a workaround for this. Please let me know if this works better.

**Comment by arvehj** [comment]
I assume this is fixed. Please re-open if you see this with the latest version.
