### ISSUE TITLE
Option to default to standard HDMI

### ISSUE THREAD

**Issue by rtguy** [arvehj/jvcprojectortools#12]
Many of us use Standard instead of Enhanced HDMI. It's easy to start the tool and forget to issue the command to switch to Standard. Can you please add an option to have the tool always start up already set to Standard?

**Comment by arvehj** [comment]
This is fixed in #5. Setup HDR reads the setting from the projector, and when you save your state it is reloaded the next time. I may also add a warning if there is a mismatch when loading the a curve, but I have not done this yet.
