### ISSUE TITLE
Allow negative black brightness value

### ISSUE THREAD

**Issue by rtguy** [arvehj/jvcprojectortools#13]
It may sound odd, but in certain circumstances we may want to crush black a little. For instance many 4K titles are mastered with black at 0.005 nits instead of 0. So running with a 0 nit black configuration means on projectors the black floor will be raised. In this case it is better to lower brightness a tad, so that 0.005 nits corresponds to "black".

Currently the black brightness control does not allow negative values, only 0 - 5. Can you make it accept a negative value, and have it adjust the curve accordingly? Thank you.

**Comment by arvehj** [comment]
I just pushed a change to the wip branch allows you to correct for this.

**Comment by rtguy** [comment]
Works great, thanks! With no black brightness correction only bar 64 and 68 were not blinking. With bbi of 0.002 the bars were crushed (good thing in this case) through 77, with only 81 blinking.  In case anyone reading this is wondering why - experiments on AVS have shown that slightly crushing black levels like this results in better blacks on 0.005 nit black mastered titles while not resulting in any noticeable crush in 0.0 nit black titles.

**Comment by arvehj** [comment]
Setting bbi to 0.002 is not correct. It should be 0 or 0.005. You should use bbo to make the bars blink.

**Comment by rtguy** [comment]
My situation is that with no bb control, I have bars 68 and above blinking. However I want to crush bars 77 and below, which means I need to *reduce* the brightness. Which if I understand correctly is the purpose of bbi?  bbo would just ADD to the values, and make it even brighter, right? When I set bbi to 0.002, then it crushes bars through 77 as desired, and the only bars that are blinking are 81 and above. Which is exactly what I am after. Does this sound right now (it sure seems like it, as I achieved the desired result with bbi 0.002), or am I missing something fundamentally here?

**Comment by arvehj** [comment]
If you want to crush bars 77 and below bbi should be set to 0.005, not 0.002. With bbi 0.002 bar 77 should not be black. If it is you bbo setting needs to be raised, or changes to reference white will also affect which bars are visible.

**Comment by rtguy** [comment]
Thanks. OK so please allow me to clarify. I just had another look at black clipping patterns and after I adjusted the brightness scale I see my bbi/bbo was wrong. I reset both to 0 and Pw. Bars in the mid 90s and up were flashing but not down to 81.  I had to use bbo of 0.0003 to get bars down to 81 to flash, and 77 and lower to not flash (purposely crushed). Make sense?

Now to clarify your other point please - in what circumstances does it make sense to use both a bbo and bbi value together? I thought bbi was just a inverse of bbo?  So IOW I thought bbi of 0.002 was the same as bbo of -0.002?

**Comment by arvehj** [comment]
bbi is subtracted from the effective (virtual) bbo value, not from the value you enter for bbo. If you enable auto-plot-and-clear (e.g. "pa 1") and set bbo and bbi to 1 you can see how the curve changes when you change the reference white and max brightness.
