### ISSUE TITLE
Support for creation of HLG curves

### ISSUE THREAD

**Issue by rtguy** [arvehj/jvcprojectortools#18]
I have used your tools with great success in the past to create a custom HDR10 curve for my low nit setup. support creation of HLG curves. However, DirecTV is now using HLG for its 4K HDR channels. I would like to create a custom curve for HLG.

As I understand it, the tool does not currently support the creation of HLG curves. Is this something you could please add? How would this work? I would create a custom curve as I've done in the past for HDR10, except I would start with an HLG baseline curve instead of the standard HDR10 baseline curve? 

Thank you.

**Comment by arvehj** [comment]
HLG is supported (as well as it can be RGB gamma curves). Select eotf_hlg instead of eotf_pq.
