### ISSUE TITLE
Graph improvements

### ISSUE THREAD

**Issue by Blade1001** [arvehj/jvcprojectortools#8]
It would be useful for the graph to show x and y axis labels and titles, and possibly a grid so it is possible to accurately see by eye where the main stimulus levels occur in 5% divisions.

Different colours for each curve and a legend indicating which coloured curve is which, would also be useful. Curves could be named based on the parameters entered e.g. 800-100-560-4000-0.5-0-1

**Comment by rtguy** [comment]
I agree it would be great to have x y axis labels and titles.

**Comment by arvehj** [comment]
I have added grid labels.

**Comment by rtguy** [comment]
Didn't see those working in the build I tried last night. No axis, no labels. Sorry I posted this a few minutes ago in a different issue.

**Comment by arvehj** [comment]
The grid labels only work if auto plot and clear is enabled as they depend on the current parameter values. I'm considering making this the default or only option.

**Comment by rtguy** [comment]
The labels on the axis are squished so I can't read them. See attached. 

Also I continue to have lots of issues with the window itself - doesn't want to stay come to the foreground - have to view it by hovering over its icon in the task bar, says "unresponsive" if trying to move it from its title bar etc.  The plot window is so important to understanding what is going on when designing curves so hopefully you can improve how it functions as a "window"? Thank you,

![curve-squished](https://cloud.githubusercontent.com/assets/2348809/24068225/b2ca63a8-0b5f-11e7-8639-3307098c65fb.png)

**Comment by arvehj** [comment]
The lasted wip branch, d32b468a9296cb52db99af8e542da824634e7da4, should fix the overlapping label issue.
